# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'Finn Woelm'
description: > # this means to ignore newlines until "baseurl:"
  Hacker 💻 Social Entrepreneur 🚀 Committed to the achievement of the
  Sustainable Development Goals by 2030 🌎
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.finnwoelm.com" # the base hostname & protocol for your site
twitter_username: finnwoelm
github_username:  fwoelm
permalink: pretty

# Add Projects
collections:
  projects:
    permalink: /projects/:path/
    output: true
  mockups:
    permalink: /projects/:categories/mockup/:slug/
    output: true

# Build settings
markdown: kramdown

# Exclude vendor so that Travis does not crash
exclude: [vendor]

# Minimize stylesheets
sass:
  style: compressed

# Set Defaults
defaults:
  - scope:
      path: ""
      type: mockups
    values:
      layout: mockup
