# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: '@finnwoelm'
description: > # this means to ignore newlines until "baseurl:"
  I'm a rainbow-loving web developer.
  My passion is technology that empowers communities.
  Excited you found me. Let's co-create a world that works for all!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.finnwoelm.com" # the base hostname & protocol for your site
twitter_username: finnwoelm
github_username:  fwoelm
permalink: pretty

# Add Projects
collections:
  projects:
    permalink: /projects/:path/
    output: true

# Build settings
markdown: kramdown

# Exclude vendor so that Travis does not crash
exclude: [vendor]

# Minimize stylesheets
sass:
  style: compressed
